export type DeploymentErrorCode =
  | 'DEPLOYMENT_PRODUCTION_UNAVAILABLE'
  | 'DEPLOYMENT_STRATEGY_UNSUPPORTED'
  | 'DEPLOYMENT_BRANCH_MISMATCH'
  | 'DEPLOYMENT_REVISION_UNAVAILABLE'
  | 'DEPLOYMENT_WORKTREE_DIRTY'
  | 'DEPLOYMENT_PLAN_STALE'
  | 'DEPLOYMENT_CONFIRMATION_REQUIRED'
  | 'DEPLOYMENT_ALREADY_RUNNING'
  | 'DEPLOYMENT_NOT_FOUND'
  | 'DEPLOYMENT_BACKUP_REQUIRED'
  | 'DEPLOYMENT_MIGRATION_COMMAND_REQUIRED'
  | 'DEPLOYMENT_PACKAGE_MANAGER_UNSUPPORTED'
  | 'DEPLOYMENT_COMMAND_FAILED'
  | 'DEPLOYMENT_PRIVILEGE_REQUIRED'
  | 'DEPLOYMENT_SUDO_TICKET_NOT_DELEGATED'
  | 'DEPLOYMENT_CANCEL_NOT_AVAILABLE'
  | 'DEPLOYMENT_VERIFY_RETRY_NOT_AVAILABLE'
  | 'DEPLOYMENT_SELF_UPDATE_FAILED'
  | 'DEPLOYMENT_PROVIDER_INTEGRATION_UNAVAILABLE'
  | 'DEPLOYMENT_PROVIDER_AUTH_FAILED'
  | 'DEPLOYMENT_PROVIDER_QUOTA_EXCEEDED'
  | 'DEPLOYMENT_PROVIDER_PROJECT_NOT_FOUND'
  | 'DEPLOYMENT_PROVIDER_DEPLOYMENT_ACTIVE'
  | 'DEPLOYMENT_PROVIDER_UNAVAILABLE'
  | 'DEPLOYMENT_PROVIDER_RESPONSE_INVALID';

export class DeploymentError extends Error {
  public constructor(
    public readonly code: DeploymentErrorCode,
    message: string,
  ) {
    super(message);
    this.name = 'DeploymentError';
  }
}
